【WIP】フロントエンド研修「モジュール作成」
kaori-s/frontend2018 pull request #1
Opened 2019-01-25 08:53 UTC by kaori-s

<コンフルURL>

2019-02-04 08:54 UTC, kaori-s commented
フロントエンド研修のモジュールの作成作業が完了しましたので、ご確認のほどよろしくお願いいたします。

【確認対象ファイルのパス】
Mac：smb://fs001/テクノロジー本部/デザイン部/82_新人研修/2018_sugita/フロントエンド研修/module/src/index.html
Win：\\fs001\テクノロジー本部\デザイン部\82_新人研修\2018_sugita\フロントエンド研修\module\src\index.html

【コミットしたファイル】
css/common.css
css/about.css
index.html

2019-02-05 01:50 UTC, sumitatsuya reviewed
まだ見きれていないのでひとまず一回目です。

2019-02-05 01:50 UTC, sumitatsuya commented on module/src/css/about.css
> +  vertical-align: middle;
画像が見きれてしまっているのと、no-repeatされていないので画像調整すると複数の画像が出てしまっています。

2019-02-05 01:50 UTC, sumitatsuya commented on module/src/css/about.css
> +  margin-left: 20px;
プロパティ順が違いますので確認お願いします。
refs：https://github.com/istyle-inc/istyle-csslint-config/blob/master/configurations/stylelintrc.js

2019-02-05 01:50 UTC, sumitatsuya commented on module/src/css/about.css
> +.bfc-news .topics-title{
意味合い的に全て `topics-title` でいいでしょうか？

2019-02-05 01:50 UTC, sumitatsuya commented on module/src/css/about.css
> +.bfc-news .news-list li:nth-child(1) span::before{
確かに<span>(日付)</span>の前ではありますが、
意味合い的にはその前の文章に付随するアイコンかと思うので
```
<li><p>文章<img><span>(日付)</span></p></li>
で直接画像置く
もしくは
<li><p>文章</p><span>(日付)</span></li>
で<p>タグのafterとして配置する
```
こんな感じのほうがよさそうな気がします。

2019-02-05 01:55 UTC, sumitatsuya commented
一か所プロパティ順の指摘をさせていただきましたが、
他にも結構ありそうなので、以下で確認の上修正してみてください 🙇 
https://github.com/istyle-inc/istyle-csslint-config/blob/master/configurations/stylelintrc.js

2019-02-05 03:51 UTC, sakurainozomi commented
@kaori-s 
詳しく見れていませんが、ざっと気になった箇所です。

1. 「もっとみる」の矢印、デザインではもっと小さいですよね？（そもそもテキストなのかな？）
あと矢印部分を`<span>>></span>`でマークアップしてますが、矢印はアイコン的要素なのでCSSの疑似要素を使って組むのが自然なのでは（フロントエンドの方にも確認してみてください）
2. ブランドファンクラブ新着情報枠、新着情報のリストとその下のリンク枠（SAQULA とかトワエッセとか）の間隔がデザインに比べて狭い印象です。http://gyazo.mmdev.istyle.local/data/33a27c2320bc1753b57a2b42ba04da55.png
3. ブランドファンクラブ限定プレゼント枠やカテゴリランキングのアンカーリンク部分、デザインでは太字ですが提出課題では太字になっていないです。

1.についてはコンフルにも迷いポイントとしてあげてくれていますが、デザインと比べるとやはり別物感を感じます。こういう形の矢印アイコンはテキストをベタで`＞＞`と書く以外にもHTML特殊文字だったり画像化したり手法はいろいろあるので、どれが一番デザインを再現するのかを正しく選択できることが大切だと思います。

2019-02-05 05:15 UTC, kikkawam commented
細かい箇所の指摘ばかりでごめんなさいね(汗
（コンフルには細かいこと気にせず、と書いてあるのは読みました！）

いつも通り（普段の仕事と同様の感じ）でレビューしました。
————————
●全体＞緑のリンクのカラーが違う
link色、(hover色、PNGではわからないか)、visitedの色がどれなのか見極めよう
●左カラム＞ランキング、コインポイント＆クーポン、スペシャル＞
左右の段のアキが杉田さんの方が少し広いと思う
http://gyazo.mmdev.istyle.local/data/817ebf35f587287806d1e1204ec8e870.png
————————
●スペシャル＞1文字落ちとかしてるのでもう少しボックスの枠広げていいのでは
http://gyazo.mmdev.istyle.local/data/0be4f2d7a10cb0dc702b5cd0383d0060.png
————————
●my@cosmeで楽しめる♪＞
グラデの開始位置違う
http://gyazo.mmdev.istyle.local/data/d77151c10299ee2d6ad10c0f414f5183.png
————————
●右カラム＞ブランドファンクラブ限定プレゼント＞
アイコンが見切れてる
●〃＞商品名＞画像では太字

————————
●右カラム＞ボディローション・ミルク ランキング＞
「キャンペーン中」の文言の右側にアキができてる
http://gyazo.mmdev.istyle.local/data/02ffd5c7e4eeafe2e0b25017c43b3e77.png
●〃＞商品名のフォントサイズが違う
————————
●右カラム＞ブランドファンクラブ新着情報＞アイコンが見切れてる
●右カラム＞ブランドファンクラブ新着情報＞最後の行＞
文言と日付の間が広くなってる
http://gyazo.mmdev.istyle.local/data/0dce3faebb0d8609e708b118512c2742.png
●右カラム＞ブランドファンクラブ新着情報＞
「SAQULA〜」文言のフォントサイズ、12pxになってるけど本当は13px



お願いします！

2019-02-05 07:05 UTC, sumitatsuya commented on module/src/index.html
> +</section>
こちら右に来る画像を左のテキストより前に記述した理由はありますか。
```
<section class="mycosme">
<!-- 左のテキストエリア -->
<div>
<h2><img src="img/text_mycosme.png" alt="ｍｙ＠ｃｏｓｍｅでより楽しめる♪　お気に入りのコスメ情報をクリップしたり、他のメンバーとつながる機能が満載！"></h2>
<p class="mycosme-text">例えば・・・</p>
<ul>
<li>気になるアイテムやブランド、クチコミ、メンバーなどを見つけたら、“クリップボタン”や“お気に入り登録ボタン”でブックマーク！ My＠ｃｏｓｍｅから一覧でチェックすることができます。</li>
<li>お気に入りの写真をMyフォトに登録。その写真をプロフィールやクチコミに載せることができます。</li>
<li>一度に複数のメンバーとのメールが可能。写真もあわせて送ることができます。</li>
</ul>
<p class="mycosme-text">＠ｃｏｓｍｅメンバーになると、あなたのお気に入りの情報だけをまとめて管理することができるから、<br>＠ｃｏｓｍｅをもっと便利に、もっと楽しめます♪</p>
</div>

<!-- 右の画像エリア -->
 <p class="mycosme-image"><img src="img/mycosme_image.jpg" alt="クチコミや商品をクリップ！クチコミに画像が入れられる！MYフォトに写真をアップ！メンバー同士でメールができる！クチコミに感謝ができる！"></p>

<!-- 登録ボタン -->
<div class="registration">
<p class="registration-text">＠ｃｏｓｍｅをもっと楽しむために、<br>まずはメンバー登録からスタート！</p>
<p class="registration-button"><a href="#">メンバー登録（無料）</a></p>
</div>
</section>
```
みたいな構成のほうがよさそうですが、いかがでしょう。(styleは変わってくると思います)

2019-02-05 07:08 UTC, sumitatsuya commented on module/src/index.html
> +<h2 class="title-sarch">ビューティ検索</h2>
`title-search` ですかね。

2019-02-05 07:18 UTC, sumitatsuya commented on module/src/index.html
> +<p class="present-detaile">フラフラ対策からぷる肌まで。実感率87％ドリンク</p>
こちらも細かくてすみませんが `present-detail`  ですかね。

2019-02-05 07:43 UTC, sumitatsuya commented on module/src/css/about.css
> +  padding: 23px 24px 14px 36px;
こちらwidthとpadding指定していますがwidthは不要だと思います。
`親の635px` に対して `width: 538px;とpaddingの合計値` が満たしていないので余白がうまれてしまっています。
ちょっと説明が難しいのでもし不明点あれば聞いてください 🙇

2019-02-05 07:48 UTC, takeuchim commented
@kikkawam リンク色はデフォルト下記でcommonで設定されており。デザインがキャプチャなので、下記で統一してました。せっかくレビューしていただいたのに、いろいろ違くてすみません～！！
```
a:link {
    color: #068681;
    text-decoration: underline;
}
a:visited {
    color: #709293;
    text-decoration: underline;
}
a:hover {
    color: #07b0a9;
    text-decoration: underline;
}
a:active {
    color: #07b0a9;
    text-decoration: underline;
}
```

2019-02-06 07:50 UTC, takeuchim reviewed
総合コメントと質問に対する答えを記載しています。
https://confluence.local-i.style/confluence/pages/viewpage.action?pageId=26733265

そのほか長文になりそうなのは↓にいれてます。
https://docs.google.com/spreadsheets/d/1U18rCw_HtJZknlcwTZzWFQxa3RW0li35bYR_shJavG4/edit#gid=0

2019-02-06 07:50 UTC, takeuchim commented on module/src/css/about.css
> +  font-size: 1.2rem;
font-sizeが2個設定されています。
また、コーディングルールでは基本pxで指定になっています。

2019-02-06 07:50 UTC, takeuchim commented on module/src/css/about.css
> +
急いで作業したのか、たまに1行空いているので、詰めてください。

書式はUIコーディングガイドラインに揃えましょう。
https://github.com/istyle-inc/design/blob/master/ui-cording-guideline/recommendation_css.md#re-cs-1-%E5%9F%BA%E6%9C%AC%E6%9B%B8%E5%BC%8F

2019-02-06 07:50 UTC, takeuchim commented on module/src/css/about.css
> +  background: -webkit-gradient(linear, left top, left bottom, from(#ffffff),color-stop(70%, #ffffff),color-stop(94%, #f1eee6),to(#e9e3d8));
`#ffffff`は`#fff`のように記述できるので省略しましょう。
https://github.com/istyle-inc/design/blob/master/ui-cording-guideline/recommendation_css.md#re-cs-6-%E8%89%B2%E3%81%AE%E6%8C%87%E5%AE%9A

2019-02-06 07:50 UTC, takeuchim commented on module/src/css/about.css
> +.bfc-news .news-list li:nth-child(2)::after{
中身が空のものは削除してください。他にもあるので、最後にきちんと確認しましょう！

2019-06-14 01:36 UTC, kaori-s commented on module/src/css/about.css
> +  vertical-align: middle;
こちら対応済みです。

【対応内容】
画像を切り直ししました。

2019-06-14 01:36 UTC, kaori-s commented on module/src/css/about.css
> +  margin-left: 20px;
こちら対応済みです。

【対応内容】
cssCombを使用して、正しい順番にソートしました。

2019-06-14 01:41 UTC, kaori-s commented on module/src/css/about.css
> +.bfc-news .topics-title{
こちら対応済みです。

【対応内容】
「topics-title」と言うclass名を「category-title」に変更しました。
https://github.com/kaori-s/frontend2018/pull/1/files#diff-2e95de8a2984e6d2859c0d292c9d1af8R540

2019-06-14 01:44 UTC, kaori-s commented on module/src/css/about.css
> +.bfc-news .news-list li:nth-child(1) span::before{
こちら対応済みです。

【対応内容】
```
<li><p>文章<img><span>(日付)</span></p></li>
で直接画像置く
```
の案を採用し、以下のように修正しました。

```
            <li>
              <a href="#">オーガニックフラワーハニーでツヤ髪へ</a><span>(9/6)</span>
            </li>
```

2019-06-14 07:56 UTC, kaori-s commented on module/src/index.html
> +</section>
対応しました！

【対応内容】
ご指摘いただきました通り、左のテキストエリア→右の画像エリア→登録ボタン としました。

```
       <div class="mycosme">
          <section class="mycosme-contentArea">
            <div class="mycosme-content">
              <div class="mycosme-textArea">
                <h2><img src="img/text_mycosme.png" alt="ｍｙ＠ｃｏｓｍｅでより楽しめる♪　お気に入りのコスメ情報をクリップしたり、他のメンバーとつながる機能が満載！"></h2>
                <p class="mycosme-text">例えば・・・</p>
                <ul class="mycosme-listArea">
                  <li class="mycosme-list">気になるアイテムやブランド、クチコミ、メンバーなどを見つけたら、“クリップボタン”や“お気に入り登録ボタン”でブックマーク！ My＠ｃｏｓｍｅから一覧でチェックすることができます。</li>
                  <li class="mycosme-list">お気に入りの写真をMyフォトに登録。その写真をプロフィールやクチコミに載せることができます。</li>
                  <li class="mycosme-list">一度に複数のメンバーとのメールが可能。写真もあわせて送ることができます。</li>
                </ul>
                <p class="mycosme-text">＠ｃｏｓｍｅメンバーになると、あなたのお気に入りの情報だけをまとめて管理することができるから、<br>＠ｃｏｓｍｅをもっと便利に、もっと楽しめます♪</p>
              </div>
              <p class="mycosme-image"><img src="img/mycosme_image.jpg" alt="クチコミや商品をクリップ！クチコミに画像が入れられる！MYフォトに写真をアップ！メンバー同士でメールができる！クチコミに感謝ができる！"></p>
            </div>
            <div class="registration">
              <p class="registration-text">＠ｃｏｓｍｅをもっと楽しむために、<br>まずはメンバー登録からスタート！</p>
              <p class="registration-button"><a href="#">メンバー登録（無料）</a></p>
              <!-- /registration -->
            </div>
          </section>
          <!-- /mycosme -->
        </div>
```
https://github.com/kaori-s/frontend2018/pull/1/files#diff-2e6eafd89d95329fafb89ba2652c1649R173

2019-06-14 07:59 UTC, kaori-s commented on module/src/index.html
> +<h2 class="title-sarch">ビューティ検索</h2>
対応しました。
【対応内容】
スペルミス、修正しました。
https://github.com/kaori-s/frontend2018/pull/1/files#diff-2e6eafd89d95329fafb89ba2652c1649R109

2019-06-14 08:03 UTC, kaori-s commented on module/src/index.html
> +<p class="present-detaile">フラフラ対策からぷる肌まで。実感率87％ドリンク</p>
対応しました
【対応内容】
こちら、スペルミスの問題でしたが、そもそも不要なクラス名であったため削除しました。
https://github.com/kaori-s/frontend2018/pull/1/files#diff-2e6eafd89d95329fafb89ba2652c1649R236

2019-06-14 08:10 UTC, kaori-s commented on module/src/css/about.css
> +  padding: 23px 24px 14px 36px;
こちら対応しました！！

【対応後の数値の合計値について】
http://gyazo.mmdev.istyle.local/data/e5d8b0b1b85561c1eb6e16057afb4bdb.png

https://github.com/kaori-s/frontend2018/pull/1/files#diff-2e95de8a2984e6d2859c0d292c9d1af8R111

2019-06-14 08:11 UTC, kaori-s commented on module/src/css/about.css
> +  font-size: 1.2rem;
こちら対応しました！
【対応内容】
フォントサイズはpx指定のものの身を残しました。

2019-06-14 08:12 UTC, kaori-s commented on module/src/css/about.css
> +
こちら対応しました。
【対応内容】
Beautifyの設定を変えて、変な行が入らぬようにしました。

2019-06-14 08:35 UTC, kaori-s commented on module/src/css/about.css
> +  background: -webkit-gradient(linear, left top, left bottom, from(#ffffff),color-stop(70%, #ffffff),color-stop(94%, #f1eee6),to(#e9e3d8));
こちら対応しました

【対応内容】
#ffffffを#fffに直しました。
https://github.com/kaori-s/frontend2018/pull/1/commits/d79b333f5238caea6448663f8c7c7608c200b139#diff-2e95de8a2984e6d2859c0d292c9d1af8R488

2019-06-14 09:03 UTC, kaori-s commented on module/src/css/about.css
> +.bfc-news .news-list li:nth-child(2)::after{
対応しました！
【対応内容】
しっかりと確認し、中身が空の無いようにしました。

2019-06-18 05:55 UTC, takeuchim commented on module/src/css/about.css
> +
空行があります、削除してください。

2019-06-18 09:45 UTC, takeuchim commented on module/src/css/about.css
> +  content: "";
ダブルクォーテーションではなくて、シングルにしてください～。`content: "";` →　`content: '';`。
JSなどで変数にHTMLのタグ入れるときに、""囲みにしてしまうと、"をエスケープする必要があるため、基本シングルを利用しています。その流れでCSSのほうもシングルが基本になってます。

2019-06-18 09:45 UTC, takeuchim commented on module/src/css/about.css
> +  margin-left: 20px;
プロパティ順のっているところが、gitLabのほうに移動しました。gitLabアカウント登録すれば閲覧できるかなと思うので見れるか確認してもらえますでしょうか？
http://repos.istyle.local/istyle-inc/istyle-csslint-config/blob/master/configurations/stylelintrc.js

ちなみにcssCombの設定で↑と同じになってますか？

2019-06-19 03:22 UTC, takeuchim commented on module/src/css/about.css
> +  vertical-align: middle;
@kaori-s no-repeatの設定がされていているのを確認しました。前の組み方が違い、beforeでいれてるときはwidth、heightの指定があるので入っても入ってなくても見た目上変わらないので基本no-repeatいれないですね。あと、画像のサイズとこのwidthとheightは全く一緒なので`background-size: contain;` も指定する必要はないかと思います。

今回はいいのですが、下記のように文字数が多くなった場合に余白やロゴの下に回りこんでしまいます。今後ここの文言変えたいてなったときに、テキスト修正だけでなくスタイルも調整することになるので、できるだけUIが変わっても対応できる将来性、拡張性を考えるようにCSSを充てられるとよいかなと思います。
http://gyazo.mmdev.istyle.local/data/bee5f8a498bac1c9c3d4a5be48153164.png

2019-06-19 03:26 UTC, takeuchim commented on module/src/css/about.css
> +.bfc-news .topics-title{
@kaori-s カテゴリータイトルもまた意味合い的に違う気がします。各モジュールのタイトルにつけているかと思いますが、共通点であるのはタイトルっていう部分なので、素直に.titleでいいのではないでしょうか？
クラス名はどういうものにつけるか、どういう意味合いでつけたいかで抽象度を変えないとあとで気持ち悪くなったりします。ここらへんの命名規則は経験値もあるかと思いますが。どういうid、class名がしっくりくるかは毎回考えてみてください。

2019-06-19 03:45 UTC, takeuchim commented on module/src/css/about.css
> +#sub .bfc-news .brand-list {
この部分、デザインが反映されていませんので確認お願いします。
http://gyazo.mmdev.istyle.local/data/02cd42194cdf0920b0b6bdace1c6375f.png

2019-06-19 03:45 UTC, takeuchim commented on module/src/css/about.css
> +
空行が入っています削除してください。

2019-06-19 03:45 UTC, takeuchim commented on module/src/css/about.css
> +#sub .bfc-news .news-list li ::before {
liの前に半角スペースが開いてしまっているので、意図していない要素に対してこの指定が聞いて●が複数個表示されていますので対応お願いします。

2019-06-19 03:45 UTC, takeuchim commented on module/src/css/about.css
> +  border-width: 2px;
borderの指定って、border: 2px solid rgb(204, 204, 204); でまとめるのが一般的な書き方ですが、rbgの指定のときとかってわけないとかけないんでしたっけ？

2019-06-19 03:45 UTC, takeuchim commented on module/src/css/about.css
> +  left: 0px;
0はpx省略してください。

2019-06-19 03:45 UTC, takeuchim commented on module/src/css/about.css
> +  content: "";
contentは並び順的に一番下です。

2019-06-19 03:45 UTC, takeuchim commented on module/src/css/about.css
> +  background-image: url(../img/icon_emoji_shine.png);
並び順的にはbackground系はmarginとvertical-alignとかの間です。

2019-06-19 03:45 UTC, takeuchim commented on module/src/css/about.css
> +  background-image: url(../img/icon_emoji_heart.png);
ここもbackground系の並び順が違います。

2019-06-19 03:45 UTC, takeuchim commented on module/src/css/about.css
> +#sub .bfc-news ul li .icon-shine {
HTML的にキラキラとかハートは文書に入りますかね？装飾的なものな気がしますが。

2019-06-19 03:45 UTC, takeuchim commented on module/src/css/about.css
> +#sub .bfc-news .news-list li {
不明な場合はデザイナーやディレクターに確認ですが、news-listのリンク範囲は、日付まですべて含めてだと想定されます。

2019-06-19 03:45 UTC, takeuchim commented on module/src/css/about.css
> +  padding-bottom: 0px;
0はpxなしでおねがいします。

2019-06-19 03:45 UTC, takeuchim commented on module/src/css/about.css
> +.bfc-news .news-list li:nth-child(1) span::before{
@kaori-s いろいろ組み方気になる点ありました。細かい部分に関してはCSSに直接コメントしてますのでそちら確認をお願いします。

2019-06-19 04:24 UTC, takeuchim commented on module/src/index.html
> +          <p class="more"><a href="#">プレゼントをもっとみる</a><span>>></span></p>
spanの中に「>>>」がありますが、これHTML文書的には意味ない装飾要素なので削除してください。
大きさ決めて背景画像で表示し、この「>>>」がユーザーからは見えないようになってますが、HTML的には存在します。装飾なので背景かbefore、afterでいれるなどでいいのでは？

2019-06-19 04:24 UTC, takeuchim commented on module/src/index.html
> +<!DOCTYPE html>
最初HTMLインデントなしにしてもらったと思うんですが、下記コミットでインデントが入ってしまっています。エディタで勝手になるようになってる場合は意図しないところまで実装時に修正が入ってしまいプルリクが見づらくなったり、そのサービスのルールに反することになります。自分で入れたのであれば修正してもらい、意図しない修正をエディタがしないように設定を確認してください。

https://github.com/kaori-s/frontend2018/pull/1/commits/0bed9d9912756fcd4298858a93632852341dd98e

2019-06-19 04:24 UTC, takeuchim commented on module/src/css/about.css
> +  background: -webkit-gradient(linear, left top, left bottom, from(#ffffff),color-stop(70%, #ffffff),color-stop(94%, #f1eee6),to(#e9e3d8));
〇

2019-06-19 04:54 UTC, takeuchim commented on module/src/index.html
> +      <!-- /header -->
終了コメントはこの形でt統一してください。
`<!-- /header --></header>`

2019-06-19 04:54 UTC, takeuchim commented on module/src/index.html
> +</section>
〇

2019-06-19 04:55 UTC, takeuchim commented on module/src/index.html
> +<h2 class="title-sarch">ビューティ検索</h2>
〇

2019-06-19 04:57 UTC, takeuchim commented on module/src/index.html
> +<p class="present-detaile">フラフラ対策からぷる肌まで。実感率87％ドリンク</p>
@kaori-s クラス名削除は承知しましたがたとえばあとでこのpだけにこの指定したいとかって場合に困るので基本何か当てておいたほうがよいのかなとは思います。

2019-06-19 05:04 UTC, takeuchim commented on module/src/css/about.css
> +
@kaori-s いまだに空行ちょこちょこ入っているので、最終チェックは自分の目で行ってください。自動化も開発効率上げる一つの手段かもしれませんが、機械は完璧に思い通りはやってくれないことが多いです。

2019-06-19 05:08 UTC, takeuchim commented on module/src/css/about.css
> +  font-size: 62.5%;
インデントはハードタブでお願いいします。今半角２つになっています。

2019-06-19 05:08 UTC, takeuchim commented on module/src/css/about.css
> +  background: -webkit-gradient(linear, left top, left bottom, from(#7db9e8), color-stop(0%, #f4f2ec), color-stop(69%, #faf9f7), to(#ffffff));
#fffに省略しましょう～。これ以外もあるので検索して修正してみてください。

2019-06-19 05:08 UTC, takeuchim commented on module/src/css/about.css
> +  border-top: dotted 1px #bfb7ac;
borderは、1px dotted #bfb7ac; の順番で記述お願いします。

2019-06-19 05:08 UTC, takeuchim commented on module/src/css/about.css
> +.bfc-news .news-list li:nth-child(2)::after{
中身が空のセレクタがないことを確認しました！

2019-06-19 05:17 UTC, takeuchim requested changes
@kaori-s コード部分に関してコメントの中身確認とフィードバックしてますので確認お願いします。

フィードバックシートも合わせて、
https://docs.google.com/spreadsheets/d/1U18rCw_HtJZknlcwTZzWFQxa3RW0li35bYR_shJavG4/edit#gid=0

2019-06-19 05:17 UTC, takeuchim commented on module/src/css/about.css
> +  vertical-align: middle;
diplay:flexを利用する場合に縦位置揃えたいときは、 `vertical-align: middle;` ではなくて `align-items: center` をつかったほうがよいです。この指定あってもなくても何も変わらない状態です。

2019-06-19 05:17 UTC, takeuchim commented on module/src/css/about.css
> +  vertical-align: middle;
ここと同様。
https://github.com/kaori-s/frontend2018/pull/1/files#diff-2e95de8a2984e6d2859c0d292c9d1af8R77

2019-06-20 06:53 UTC, kikkawam commented
@kaori-s 
櫻井さんがご指摘の箇所と私の箇所確認しました。
前回は大丈夫だったのに（今となっては多分、なのですが…勘違いだったらすみません！！）、
追加でこちらが変わっているように思います。
①右カラム＞ブランドファンクラブ新着情報下の囲み＞
リンクが外れてます。（右が杉田さん）
http://gyazo.mmdev.istyle.local/data/a0b37d1ea1b6332dd82eab78317738af.png
②右カラム＞ブランドファンクラブ新着情報＞↑リストの高さがお手本よりも少し高そう
③右カラム＞カテゴリランキング＞
３位がないのはいいんでしたっけ？？（右が杉田さん）
http://gyazo.mmdev.istyle.local/data/20a859ed70f929bc346e9c94d58fd442.png

余談ですが、この場合「解答」ではなく「回答」ですね！

以上です。よろしくお願いいたします。

2019-06-24 01:59 UTC, kaori-s commented on module/src/css/about.css
> +  content: "";
対応しました。
【対応】
content: ""; →　content: '';
に修正しました。

2019-06-24 02:00 UTC, kaori-s commented on module/src/css/about.css
> +
対応しました。
【対応】
空行を削除しました

2019-06-24 02:04 UTC, kaori-s commented on module/src/css/about.css
> +.bfc-news .news-list li:nth-child(2)::after{
申し訳ありませんが、こちら見当たりませんでした。
最終チェックとして中身が空のセレクタが無いようにしましたので、ご確認のほどよろしくお願いいたします。

2019-06-24 02:04 UTC, kaori-s commented on module/src/css/about.css
> +
対応しました。
【対応】
空行を削除しました

2019-06-24 02:28 UTC, kaori-s commented on module/src/css/about.css
> +  vertical-align: middle;
対応しました
【対応内容】
width、heightの指定を優先し、no-repeatは削除しました。
また、background-size: contain;も不要な箇所については削除しました。

2019-06-24 02:32 UTC, kaori-s commented on module/src/css/about.css
> +.bfc-news .topics-title{
対応しました
【対応方法】
`.category-title` を `.title` に修正しました。
ご確認のほどよろしくお願いいたします。

2019-06-24 02:36 UTC, kaori-s commented on module/src/index.html
> +<p class="present-detaile">フラフラ対策からぷる肌まで。実感率87％ドリンク</p>
対応しました
【対応内容】
> あとでこのpだけにこの指定したいとかって場合に困るので基本何か当てておいたほうがよいのかなとは思います。
クラス名、`present-detail` を追記しました。

2019-06-25 03:26 UTC, kaori-s commented on module/src/css/about.css
> +  margin-left: 20px;
gitLabのアカウントは持っていますが、頂いたURL先のページが閲覧できませんでした。
こちらあとで口頭でご説明いただく際に教えて頂きたく思います

2019-06-25 03:29 UTC, kaori-s commented on module/src/css/about.css
> +  border-width: 2px;
対応しました。
【対応内容】
border: 2px solid rgb(204, 204, 204); に書き換えました。

2019-06-25 03:36 UTC, kaori-s commented on module/src/css/about.css
> +  left: 0px;
対応しました。
【対応内容】
0の部分のpxを削除しました

2019-06-25 03:40 UTC, kaori-s commented on module/src/css/about.css
> +  content: "";
対応しました。

2019-06-25 03:41 UTC, kaori-s commented on module/src/css/about.css
> +  background-image: url(../img/icon_emoji_shine.png);
対応しました。

2019-06-25 03:41 UTC, kaori-s commented on module/src/css/about.css
> +  background-image: url(../img/icon_emoji_heart.png);
対応しました。

2019-06-25 03:42 UTC, kaori-s commented on module/src/css/about.css
> +  padding-bottom: 0px;
対応しました。

2019-06-25 03:42 UTC, kaori-s commented on module/src/css/about.css
> +  background-image: url(../img/icon_emoji_heart.png);
対応しました。

2019-06-25 06:28 UTC, kaori-s commented on module/src/css/about.css
> +#sub .bfc-news ul li .icon-shine {
対応しました
【対応内容】
キラキラやハートなどのアイコンはafterでテキストの後に入れました。

2019-06-25 06:28 UTC, kaori-s commented on module/src/css/about.css
> +#sub .bfc-news .news-list li {
対応しました
【対応内容】
リンク範囲に日付も入れました

2019-06-25 06:28 UTC, kaori-s commented on module/src/index.html
> +          <p class="more"><a href="#">プレゼントをもっとみる</a><span>>></span></p>
対応しました
【対応内容】
>>のアイコンはafterでテキストの後に入れました。

2019-06-25 06:29 UTC, kaori-s commented on module/src/index.html
> +<!DOCTYPE html>
対応しました。
【対応内容】
HTMLのインデントを無くしました。

2019-06-25 06:32 UTC, kaori-s commented on module/src/index.html
> +      <!-- /header -->
対応しました。

2019-06-25 09:55 UTC, kaori-s commented on module/src/css/about.css
> +  font-size: 62.5%;
対応しました。

2019-06-25 09:58 UTC, kaori-s commented on module/src/css/about.css
> +  background: -webkit-gradient(linear, left top, left bottom, from(#7db9e8), color-stop(0%, #f4f2ec), color-stop(69%, #faf9f7), to(#ffffff));
対応しました！！

2019-06-27 00:59 UTC, kaori-s commented on module/src/css/about.css
> +  border-top: dotted 1px #bfb7ac;
対応しました
【対応内容】
borderは「太さ　種類　色」の順になるようにしました

2019-06-27 01:08 UTC, kaori-s commented on module/src/css/about.css
> +  vertical-align: middle;
対応しました！
`vertical-align: middle;`　を`align-items: center`　にしました。

2019-06-27 01:08 UTC, kaori-s commented on module/src/css/about.css
> +  vertical-align: middle;
対応しました！

2019-06-27 03:21 UTC, kikkawam commented
@kaori-s
橘川指摘箇所、②③確認しました！
①については、リンクはつきましたが、↓1つ目のリストの右のアキが他より狭いです。
http://gyazo.mmdev.istyle.local/data/e90b99e5853fa6c21ec2e89f6494acf8.png
よろしくお願いいたします。

2019-06-27 03:26 UTC, kikkawam commented
@kaori-s 
もう一つ追加です。↓ビューティ検索が今度は崩れちゃいましたね。
http://gyazo.mmdev.istyle.local/data/e192ff4d6585c4f0d122ec1ac5f009a4.png

2019-06-27 07:59 UTC, takeuchim commented
@kaori-s コイン・ポイント＆クーポンの貯金箱の画像が途切れてるのか高さ指定が高すぎるのか、何か見えてます。
http://gyazo.mmdev.istyle.local/data/0a42bcdda6ea6c28e7b666072c86cc0e.png

2019-07-01 07:19 UTC, kaori-s commented on module/src/css/about.css
> +#sub .bfc-news .news-list li ::before {
対応しました
【対応内容】
liの前にある半角を消しました。

2019-07-01 07:32 UTC, kaori-s commented on module/src/css/about.css
> +#sub .bfc-news .brand-list {
対応しました

2019-07-01 07:32 UTC, kaori-s commented on module/src/css/about.css
> +
対応しました

2019-07-02 05:35 UTC, kaori-s commented on module/src/css/about.css
> +  margin-left: 20px;
対応しました

2019-07-03 07:35 UTC, kikkawam commented
@kaori-s 
右カラム＞ブランドファンクラブ新着情報下の囲みと
ビューティ検索の崩れ修正されてること確認しました。

竹内さんの↓これまだ直していない感じですか？検証機のwin IE10で見ると引き続き↓同じ状態でした

> また、ＩＥにて表示が盛大に崩れている様子。原因探っていただけますか？
> http://gyazo.mmdev.istyle.local/data/93ddb1c7119186f6bd2d468cf4da265d.png

2019-07-03 08:07 UTC, kaori-s commented
@takeuchim @kikkawam 
IE10での表示崩れの件ですが、検証機で確認する際に「開発者ツール」のバージョン指定がデフォルトで7になっているため崩れているデザインが表示されてしまったのではないかと思われます。
開発者ツールのバージョン指定を10や11にすると表示崩れがありませんでした。

一応、互換表示の対策として
`<meta http-equiv="X-UA-Compatible" content="IE=11"/>`を、追記致しました。

2019-07-03 08:44 UTC, takeuchim commented
@kaori-s 

基本は入れなくてもIE11の規定の表示になるはず？
IEがこのサイトは古い表示モードじゃないと見れないって判定しているので、HTMLコードを少しずつ削除したりしてどこが原因か根本を探らないとあとで何かあったときとか対応に困ってしまいます。

急ぎや調査してもどうしても不明な場合は入れて、引き続き調査かなと思いますが、
もしいれるとしたらIE11じゃなくて、edgeですね。
７で判定されてしまうってよっぽどのなんかある気がします。

```
<meta http-equiv="X-UA-Compatible" content="IE=edge">
```

2019-07-09 02:41 UTC, kaori-s commented
IEの互換表示について、様々なパターンで確認しましたところ共有サーバーで受け取ったデータは一度windowsで見る際にはデスクトップに移してから開くと崩れないということがわかりました。

以下、試したパターンです。
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
１：コンフルにあった圧縮された課題フォルダを共有サーバーへ
A：共有サーバーフォルダ内でmacで展開→IE7で表示
B：共有サーバーフォルダ内でwinで展開→IE7で表示

２：１の圧縮された課題フォルダをwindowsのデスクトップへ
C：winのデスクトップ上でフォルダを展開→IE11で表示

３：macのデスクトップ上でsrc_macというフォルダを作成して圧縮する。windowsのデスクトップ上でsrc_winというフォルダを作成して圧縮する。どちらも共有サーバーにあげる
D：winの共有サーバー上でsrc_macを開く→IE7表示
E：winの共有サーバー上でsrc_winを開く→IE11表示
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

2019-07-16 07:04 UTC, takeuchim commented
@kaori-s パターンの確認ありがとうございました。
共有サーバーのものを一度ローカルにＤＬして確認すれば問題なさそうですね。

ちなみに、３のパターンに関して手順が不明でした。共有サーバーに圧縮したやつがおかれていて、それをローカルに展開し、ローカルで確認するであってる？？

2019-07-16 07:39 UTC, takeuchim commented on module/src/index.html
> +<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
基本バックスラッシュなしで統一なので、「/」は削除してください。

2019-07-16 07:39 UTC, takeuchim commented on module/src/css/about.css
> +	７flex-wrap: wrap;
上に1行あいているのと、「７」があたまにありますがこれ動作してますか？

2019-07-16 07:39 UTC, takeuchim commented on module/src/css/about.css
> +html{
全体に関わりますが、セレクタの後ろは半角スペースをあけてください。

2019-07-16 07:39 UTC, takeuchim commented on module/src/css/about.css
> +
作業し終わったあとに、ファイル内全部チェックしてますか？
空行が開いています削除してください。

2019-07-16 07:39 UTC, takeuchim commented on module/src/css/about.css
> +	margin-top: -2px;
サブカラムをマイナス2pxしてますが、デザインに合わせるためですか？
この場合1ページで完結しているからいですが、基本的に大きなレイアウトにマイナスマージン使うのは、あとで事故る可能性や拡張性がなくなるためしません。デザインと多少ずれてしまってもここはほかの方法でどうにかできないかを検討すべきかと思います。

2019-07-16 07:39 UTC, takeuchim commented on module/src/css/about.css
> +  vertical-align: middle;
contain検索したら、widthとheightと併用されているところ下記などありました。no-repeatないとだめそうでした？

https://github.com/kaori-s/frontend2018/pull/1/files#diff-2e95de8a2984e6d2859c0d292c9d1af8R648
https://github.com/kaori-s/frontend2018/pull/1/files#diff-2e95de8a2984e6d2859c0d292c9d1af8R729
https://github.com/kaori-s/frontend2018/pull/1/files#diff-2e95de8a2984e6d2859c0d292c9d1af8R742

2019-07-16 07:40 UTC, takeuchim commented on module/src/css/about.css
> +  margin-left: 20px;
対応ありがとうございます。大まか見た限り大丈夫そうです。細かいですが、大人数で作業する上で大事になってくるので続けていただければと思います。

2019-07-16 07:41 UTC, takeuchim commented on module/src/css/about.css
> +.bfc-news .topics-title{
〇

2019-07-16 07:42 UTC, takeuchim commented on module/src/index.html
> +<p class="present-detaile">フラフラ対策からぷる肌まで。実感率87％ドリンク</p>
〇

2019-07-16 09:16 UTC, takeuchim commented on module/src/css/about.css
> +  padding: 23px 24px 14px 36px;
@kaori-s paddingで余白指定しているから、横幅の設定は不要かなと思います。メインカラムいっぱいに広がっていいのであれば、width:600pxは削除してもdiv要素は横幅成り行きになるから。もし言っていることが不明であれば口頭で説明します。

2019-07-16 09:39 UTC, takeuchim commented on module/src/css/about.css
> +	font-size: 62.5%;
bodyに12pxを指定しているので、この「62.5%」ってどこへの指定になりますか？？

2019-07-16 09:39 UTC, takeuchim commented on module/src/css/about.css
> +
@kaori-s 下記まだ空行あるようです。最後にコミットしたファイルを自分の目で空行ないか確認してください。
https://github.com/kaori-s/frontend2018/pull/1/files#r303763099
https://github.com/kaori-s/frontend2018/pull/1/files#r303763519

2019-07-16 09:39 UTC, takeuchim commented on module/src/css/about.css
> +  font-size: 1.2rem;
〇

2019-07-16 09:41 UTC, takeuchim commented on module/src/css/about.css
> +
〇

2019-07-16 09:41 UTC, takeuchim commented on module/src/css/about.css
> +.bfc-news .news-list li:nth-child(2)::after{
〇

2019-07-16 09:43 UTC, takeuchim commented on module/src/css/about.css
> +  content: "";
@kaori-s ここにまだいるようです！
https://github.com/kaori-s/frontend2018/pull/1/files#diff-2e95de8a2984e6d2859c0d292c9d1af8R50

2019-07-16 09:46 UTC, takeuchim commented on module/src/css/about.css
> +#sub .bfc-news .brand-list li:nth-child(4){
4つ目だけ、前にマージンをなくしてますが、テキストに入る文字数はこの文字数固定ではなくて動的と考えられます。4つ目ではなくて3つ目のリストが一番前に来る可能性もあります。それを考慮して実装をしなおしてください。

2019-07-16 09:46 UTC, takeuchim commented on module/src/css/about.css
> +#sub .bfc-news .brand-list {
〇

2019-07-16 09:46 UTC, takeuchim commented on module/src/css/about.css
> +
〇

2019-07-16 09:48 UTC, takeuchim commented on module/src/css/about.css
> +#sub .bfc-news .news-list li ::before {
〇

2019-07-16 09:49 UTC, takeuchim commented on module/src/css/about.css
> +  border-width: 2px;
〇

2019-07-16 09:50 UTC, takeuchim commented on module/src/css/about.css
> +  left: 0px;
〇

2019-07-16 09:50 UTC, takeuchim commented on module/src/css/about.css
> +  content: "";
〇

2019-07-16 09:51 UTC, takeuchim commented on module/src/css/about.css
> +  background-image: url(../img/icon_emoji_shine.png);
〇

2019-07-16 09:52 UTC, takeuchim commented on module/src/css/about.css
> +  background-image: url(../img/icon_emoji_heart.png);
〇

2019-07-16 09:52 UTC, takeuchim commented on module/src/css/about.css
> +#sub .bfc-news ul li .icon-shine {
〇

2019-07-16 09:53 UTC, takeuchim commented on module/src/css/about.css
> +#sub .bfc-news .news-list li {
〇

2019-07-16 09:54 UTC, takeuchim commented on module/src/css/about.css
> +  padding-bottom: 0px;
〇

2019-07-16 09:54 UTC, takeuchim commented on module/src/index.html
> +          <p class="more"><a href="#">プレゼントをもっとみる</a><span>>></span></p>
〇

2019-07-16 09:55 UTC, takeuchim commented on module/src/index.html
> +<!DOCTYPE html>
〇

2019-07-16 09:59 UTC, takeuchim commented on module/src/index.html
> +</div>
終了コメントが抜けていますので入れてください。

2019-07-16 09:59 UTC, takeuchim commented on module/src/index.html
> +</div>
終了コメントが抜けていますので入れてください。

この付近で下記も。
https://github.com/kaori-s/frontend2018/pull/1/files#diff-2e6eafd89d95329fafb89ba2652c1649R257
https://github.com/kaori-s/frontend2018/pull/1/files#diff-2e6eafd89d95329fafb89ba2652c1649R259

2019-07-16 09:59 UTC, takeuchim commented on module/src/index.html
> +</div>
上のほう見たら全体的に抜けている部分あるので、コメント入れてもらえますか～？

2019-07-16 09:59 UTC, takeuchim commented on module/src/index.html
> +      <!-- /header -->
` <!-- /header -->` の部分はＯＫです〇
他のdivなどの終了コメントも同じように入れてもらえますか？別途コメントしてます！

2019-07-16 09:59 UTC, takeuchim commented on module/src/css/about.css
> +  font-size: 62.5%;
〇

2019-07-16 10:00 UTC, takeuchim commented on module/src/css/about.css
> +  background: -webkit-gradient(linear, left top, left bottom, from(#7db9e8), color-stop(0%, #f4f2ec), color-stop(69%, #faf9f7), to(#ffffff));
〇

2019-07-16 10:00 UTC, takeuchim commented on module/src/css/about.css
> +  border-top: dotted 1px #bfb7ac;
〇

2019-07-16 10:01 UTC, takeuchim commented on module/src/css/about.css
> +  vertical-align: middle;
〇

2019-07-16 10:02 UTC, takeuchim commented on module/src/css/about.css
> +  vertical-align: middle;
〇

2019-07-16 10:06 UTC, takeuchim commented on module/src/css/about.css
> +	position: absolute;
position配置しているため、文字数が大きくなると画像にかぶります。文字数が増えたとしても被らないように考えてもらえますか？
http://gyazo.mmdev.istyle.local/data/ea984964ce34e3b64373dcd8750ea20b.png

2019-07-18 02:34 UTC, kaori-s commented on module/src/css/about.css
> +	７flex-wrap: wrap;
申し訳ありませんでした。こちら「7」を消去しました。

2019-07-18 02:44 UTC, kaori-s commented on module/src/index.html
> +<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
「/」を削除しました。

2019-07-18 02:45 UTC, kaori-s commented on module/src/css/about.css
> +html{
こちら、セレクタの後ろに半角スペースを追加しました

2019-07-18 02:49 UTC, kaori-s commented on module/src/css/about.css
> +	font-size: 62.5%;
意味の無い指定なので削除しました

2019-07-18 02:58 UTC, kaori-s commented on module/src/css/about.css
> +#sub .bfc-news .brand-list li:nth-child(4){
こちら、#sub .bfc-news .brand-list li:nth-child(1)にmargin-right: 4px;を追記するようにしました。

2019-07-18 03:18 UTC, kaori-s commented on module/src/index.html
> +</div>
【回答】
こちら全てのに終了コメントを追記しました

2019-07-18 03:18 UTC, kaori-s commented on module/src/index.html
> +</div>
【回答】
こちら全てのに終了コメントを追記しました

2019-07-18 05:49 UTC, kaori-s commented on module/src/css/about.css
> +	position: absolute;
こちら対応しました。
文字数が多くなると画像も一緒に下がるようにしました。
http://gyazo.mmdev.istyle.local/data/3cb3bb38f9cba175e7227c2366476aae.png

2019-07-18 05:50 UTC, kaori-s commented on module/src/css/about.css
> +	margin-top: -2px;
Photoshopデータと重ねてデザインのずれを確認しましたが、問題なさそうでしたので削除しました。

2019-07-19 03:08 UTC, takeuchim commented on module/src/index.html
> +<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
〇

2019-07-19 03:09 UTC, takeuchim commented on module/src/css/about.css
> +	７flex-wrap: wrap;
〇

2019-07-19 03:09 UTC, takeuchim commented on module/src/css/about.css
> +html{
〇

2019-07-19 03:10 UTC, takeuchim commented on module/src/css/about.css
> +
〇

2019-07-19 03:10 UTC, takeuchim commented on module/src/css/about.css
> +	margin-top: -2px;
〇

2019-07-19 03:12 UTC, takeuchim commented on module/src/css/about.css
> +	font-size: 62.5%;
〇

2019-07-19 03:28 UTC, takeuchim commented on module/src/css/about.css
> +#sub .bfc-news .brand-list li:nth-child(4){
〇
これでも間違いではないのですが、隣接（+）のセレクタは結構混乱する人多い気がします。言い換えないとわかりづらいですよね。
他の人がかいたCSSを解読して修正しないといけないことが多いので、直観でわかりやすいCSSを書いてあげるとメンテナンス性、開発効率向上につながります。
```
■今書いてある設定
#sub .bfc-news .brand-list li + li {　　→liの次のliがあった場合に後ろにあるli要素に適用。言い換えると、1つ目以外のli要素に適用。
	margin-right: 6px;
}

#sub .bfc-news .brand-list li:nth-child(1) {　→1つ目のli要素に適用
	margin-right: 4px;
}
```
他にもいろいろな書き方があります。あんまりnotとか多様するのも、頭の中でこれじゃないものに適用するって想像大変ですよね。答えはないですが、できるだけみんなが直観的にわかるようなセレクタの書き方を研究してみてください。
```
■こういう書き方もあるよサンプル
#sub .bfc-news .brand-list li {　→すべてのli要素に適用
	margin-right: 6px;
}
#sub .bfc-news .brand-list li:first-child { →1番目だけ上書き
	margin-right: 4px;
}
}
```
li:first-childとli:nth-child(1) は同じ意味です。こういう書き方もあるってのを覚えておくとよいかと思います。
}
```
■上書きではなくて指定もできるよサンプル
#sub .bfc-news .brand-list li:not(:first-child) {　→notを使って、1番目以外に指定
	margin-right: 6px;
}
#sub .bfc-news .brand-list li:first-child { →1番目だけに指定
	margin-right: 4px;
}
```

2019-07-19 03:37 UTC, takeuchim commented on module/src/index.html
> +</section>
sectionの終了タグコメントが抜けています。

2019-07-19 03:37 UTC, takeuchim commented on module/src/index.html
> +<section class="mycosme-contentArea">
「mycosme-contentArea」のクラス名ですが、サービスごとによってアッパーキャメルケース使うことはあるのですが、基本的にはハイフンと小文字で構成してください。他にもあったので、修正をお願いします。

2019-07-19 03:37 UTC, takeuchim commented on module/src/index.html
> +</div>
抜けていたところあったので、コメントしました。
https://github.com/kaori-s/frontend2018/pull/1/files#diff-2e6eafd89d95329fafb89ba2652c1649R186

2019-07-19 03:38 UTC, takeuchim commented on module/src/css/about.css
> +	position: absolute;
〇

2019-07-19 03:44 UTC, takeuchim reviewed
終了コメントが抜けているところがあったのでコメントしました。
あと、class名で小文字ハイフンで統一されていないところがあったので追加コメントしてます。
https://github.com/kaori-s/frontend2018/pull/1/files#r305191243

下記ブラウザ挙動としては問題ないんですが、複数人が作業する上でセレクタ指定のアドバイス的な感じです。
https://github.com/kaori-s/frontend2018/pull/1#discussion_r305190071

【回答】
書き方サンプルありがとうございます。
大変参考になります。隣接セレクタや間接セレクタはガンガン使ってました。
チームでの作業の時に混乱してしまうことを考えていませんでした。
以後、ちゃんと配慮し書き方サンプルのように上書きするようなcssを記述したり、工夫したいと思います。

2019-07-19 05:19 UTC, kaori-s commented on module/src/index.html
> +<section class="mycosme-contentArea">
class名がアッパーキャメルケースになってしまっている部分は以下のようにしました。
ご確認のほどよろしくお願い致します。
.mycosme-contentArea→.mycosme-content-wrap
.mycosme-textArea→.mycosme-text-wrap
.mycosme-listArea→.mycosme-list-wrap

2019-07-19 05:20 UTC, kaori-s commented on module/src/index.html
> +</section>
class名がついてるsectionの終了タグにコメントを追記しました。

2019-07-22 07:33 UTC, takeuchim commented on module/src/index.html
> +	<!-- /mycosme-content-wrap --></section>
インデントついちゃってますね。エディタの設定かな？
コミットする前に、git diffって打つとどういう差分がでるからそれで意図しない差分でてないか確認してからコミットしたほうがいいかもね。

2019-07-22 07:33 UTC, takeuchim commented on module/src/index.html
> +<section class="mycosme-contentArea">
〇

2019-07-22 07:35 UTC, takeuchim reviewed
最後これ1つだけやって、ひとまずこの研修については終わりにしましょうか！

2019-07-26 01:04 UTC, takeuchim commented
@kaori-s インデントの修正ありがとうございました。そこだけじゃなくて他にもあったんですね。ファイル全体見直していただき感謝です。

私含めフロントエンドの分は、LGTM!です。
が、まだまだやろうと思えばいろいろ改善できます時間あるときにどうしたらよいか懲りずに考えてみてくださいね＾＾

デザイン再現性部分に関しては、櫻井さん、橘川さんに大丈夫かどうか引き続き確認ください。
終わったら、このプルリクをマージしていただければと～～。

↓はこのコーディング課題での感想と今後のアドバイスとして書かせていただきます。

----

今回は簡単なデザインを1人で1ページ起こす課題に取り組んでもらいました。UIコーディングガイドラインの一部やアットコスメでのルールなどをを適用してもらい、今までの書き方の癖などを均してもらったという認識です。

かなり覚えることが多くて大変だったかと思います。
最初のころに比べたら、HTMLの構造化やCSSの書き方もきれいになってきたと思います。

下記今後のアドバイスとして記載しますね。

傾向として1つなおしたら、違うところに影響があるので、コミットする前に意図しない差分が発生していないか確認しましょう。

デザイン再現性も結構突っ込まれてましたが、確認投げる前に推奨・対応ブラウザで崩れがないか、デザインとあっているかを１つずつ確認しましょう。
最初は確認するの時間かかりますが、段々見るポイントがわかってきますので、忍耐強く細かいところまで自信を持って投げましょう。

コードってに関して表から見えない部分なので、ないがしろにされることが多いですが、HTMLは特にSEOに関係しますし。無駄なコードかかなけえれば、容量も少なくなる。さらに、だれもが見てわかりやすいコードはメンテナンス性も高くなる。プロのフロントエンド、というかエンジニアの方々は一切無駄なコードは書きません。1行1行すべてに意味があります。
でも、これはすべての要素配置に意味があるって考えるとデザインにも共通しているかもですね。

フロントエンドのみんなは、この課題よりも難易度のさらに高いUI、複数画面に同じモジュールがでてCSS設計どうしようとか悩むものや、複数人で作業してとか、さらにいろんなことを考慮してます。
そのレベルに一気に行くのは無理なので、今回課題として挙がったことをきちんと確実にできるようにしましょう。今後も機会見つけてコーディングしてみてください。フロントエンド研修お疲れ様でした！！！

2019-07-29 07:22 UTC, kikkawam commented
@kaori-s 
 ↓こちらですね！

> あと今更ですみません（汗
> 豚のイラストbackground_coin.jpgの画質が粗いのをもっと綺麗にしたいです＞＜

2019-08-19 02:43 UTC, kikkawam commented
@kaori-s 
画像確認しました。
画像の画質が粗いのではなくて、画像のサイズ設定が歪んでいるようですね。
↓左は課題zipのpng：右はブラウザで表示した杉田さんのキャプチャ
http://gyazo.mmdev.istyle.local/data/a74b7b3cbeed8ff200e4d95cf671ad3e.png

縦長に伸びているようです。よろしくお願いいたします。

2019-08-19 04:02 UTC, kikkawam commented
@kaori-s ↑問題ございません〜
櫻井さん、橘川分全てOKです。

2019-08-19 06:20 UTC, merged